### ISSUE TITLE
Can see it flicker when the game list changes

### ISSUE THREAD

**Issue by ZomBagus** [SimonS/jankteki#1]
When the list of games change there is a brief flicker where the list reverts to the top and then reinserts the friends list and drops down.

**Comment by SimonS** [comment]
yes, I'm looking to find a way of turning off jinteki.net's autoscroll and autorefresh - you should see the way we get around that in code. It is ugly as hell. The flickering is a consequence of this hackiness.

**Comment by SimonS** [comment]
just put a change in for this one - going to see if that stabilises over the next couple of days
