### ISSUE TITLE
Mention it is case sensitive?

### ISSUE THREAD

**Issue by ZomBagus** [SimonS/jankteki#2]
I note the friends list names are case sensitive. Is it worth mentioning this in the dialog box? I suspect you will get bug reports about this otherwise.

**Comment by SimonS** [comment]
good call - one of the next features I'm looking at adding is `right click player -> add as friend`, which will manage this somewhat. But you're right, either make that explicit, or, even better, make it case insensitive (although I'd need to make sure that duplicate usernames don't / can't exist first).

**Comment by SimonS** [comment]
added a small bit of placeholder text to this for now, will be in release 0.1.16
