### ISSUE TITLE
Would be useful to have a real name/comments field

### ISSUE THREAD

**Issue by ZomBagus** [SimonS/jankteki#5]
I would like to record the real name and possibly notes against the ID. Therefore I would quite like to have a real name field and/or a comments field alongside the ID. Possibly also a clickable star/challenge rating.

**Comment by SimonS** [comment]
This is one of the key things I want to introduce to the extension, just any extra user meta-data beyond username. It lends itself to so many future power-features (game log recording and analysis, for instance).

Top of the backlog: https://trello.com/c/MJICXIQB/12-add-notes-to-users

**Comment by SimonS** [comment]
@ZomBagus - I believe this is in and deployed. I'll be making a screencast on how it works this week.
