### ISSUE TITLE
console error when you first load a page and go to lobby

### ISSUE THREAD

**Issue by SimonS** [SimonS/jankteki#9]
just needs a quick check to see why `createFixesPanel` is firing when containers aren't on the page

**Comment by SimonS** [comment]
The problem causing this is gamelobby is not present / explicitly set to 'none' on every page. Need smarter page-check code.

**Comment by SimonS** [comment]
This also happens on watched games - we should just plain check a node exists before we 'insertBefore'

**Comment by lpoulter1** [comment]
@SimonS is this still an issue?
